### ISSUE TITLE
Review templates and incexc rules

### ISSUE THREAD

**Issue by pablodav** [CoffeeITWorks/ansible_burp2_server#40]
review the good rules written by @deajan  at https://github.com/deajan/linuxscripts/tree/master/burp/incexc

and see which ones fits on our incexc and templates.

**Comment by deajan** [comment]
Thanks Pablo. Would love to have your input on these if somehow I forgot stuff :)

**Comment by deajan** [comment]
I have added a lot of new regexes last weeks, dealing mostly with Windows 10 Store and caches, and generic exclusions.
It decreased my production backups sizes by alot (20-40%).
Do you have any exclude lists I may merge with mine ?
Aiming to have a very complete ruleset.

**Comment by pablodav** [comment]
Some of the incexc templates are here:

https://github.com/CoffeeITWorks/ansible_burp2_server/tree/master/files/incexc

But also you create your own in host_vars/group_vars as per host/group if needed or use the defaults with variable `profile_templates`

Example of defaults:

https://github.com/CoffeeITWorks/ansible_burp2_server/blob/master/defaults/main.yml#L119

All those goes to server `"{{ burp_server_clientconfdir }}/incexc` 
Where default value for var burp-server_clientconfdir is /etc/burp/clientconfdir  (See https://github.com/CoffeeITWorks/ansible_burp2_server/blob/master/defaults/main.yml#L53)

Tasks that handle this copy of files/templates are:

https://github.com/CoffeeITWorks/ansible_burp2_server/blob/master/tasks/config_burp.yml#L33

```yaml
- name: config_burp | configure profiles configured in profiles_templates
  template:
    src: profiles/profile_template.j2
    dest: "{{ burp_server_clientconfdir }}/incexc/{{ item.name }}"
  with_items: "{{ profiles_templates }}"
```

https://github.com/CoffeeITWorks/ansible_burp2_server/blob/master/tasks/config_burp.yml#L39
```yaml
- name: copy clients configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ burp_server_clientconfdir }}"
    directory_mode: yes
    force: yes
  with_items:
    - incexc
```
