### ISSUE TITLE
Debian buster asks for libssl1.0.0

### ISSUE THREAD

**Issue by adocampo** [CoffeeITWorks/ansible_burp2_server#54]
I'mtrying to install the playbook on a brand new installed debian 10, but it fails.
```
TASK [CoffeeITWorks.burp2_server : install build dependencies] ****************************************************************************
Wednesday 09 October 2019  17:42:13 +0200 (0:00:00.646)       0:00:01.967 ***** 
fatal: [192.168.10.251]: FAILED! => {"changed": false, "msg": "No package matching 'libssl1.0.0' is available"}
```
my `roles.burp2_servers.yml` 
```yaml
---

- name: burp2 servers
  become: yes
  become_method: sudo
  # environment: "{{ proxy_env }}"  # example to use behind proxy
  hosts: burp2
  # Define the list of servers and add tags so you will be able to filter the call to a tag:
  roles: 
    - role: CoffeeITWorks.burp2_server
      tags: 
        - "burp2_server_all"
        - "burp2_server"
```

my `vim vars/Debian.yml`
```yaml
---
# file: vars/Ubuntu.yml

# burp_server_packages:
#  - libssl-dev
#  - burp-core

build_dependencies:
  - make
  - pkg-config
  - check
  - g++
  - librsync-dev
  - libncurses5-dev
  - libz-dev
  - libssl-dev
  - uthash-dev
  - libyajl-dev
  - autoconf
  - automake
  - libtool
  - dh-autoreconf
  - unzip       # required to unzip from master.zip archive for example
  - openssl     # On debian 8 vagrant is not installed by default
  - libncurses5 # from package dependencies
  - libgcc1     # from package dependencies
  - libc6       # from package dependencies
  - libacl1     # from package dependencies
  - libssl1.1   # from package dependencies
  - libtinfo5   # from package dependencies
  - zlib1g      # from package dependencies
  - locales

# Repository information: http://ziirish.info/repos/README.txt
# burp_apt_sources:
#  - "deb http://ziirish.info/repos/ubuntu/{{ ansible_distribution_release }} zi-latest main"

supervisoretc_dir: "/etc/supervisor/conf.d"
supervisor_ext: "conf"
supervisor_service: supervisor
pip_installed_exe_bin_path: '/usr/local/bin'

cron_packages:
  - cron      # To enable crontab jobs

cron_service: cron
```

Any idea¿?
