### ISSUE TITLE
option to remove client from server

### ISSUE THREAD

**Issue by pablodav** [CoffeeITWorks/ansible_burp2_server#7]
add option to remove client automatically

**Comment by pablodav** [comment]
Added for testing on branch feature/7_remove_client

Test it: 

modify `requirements.yml` : 

```yaml
- src: https://github.com/CoffeeITWorks/ansible_burp2_server.git
  version: feature/7_remove_client
  name: CoffeeITWorks.burp2_server
```
Install: 

    sudo ansible-galaxy install -r requirements.yml

or install on different path: 

    ansible-galaxy install -r requirements.yml -p roles 

You must remove it if it is already installed: 

    rm -rfv /etc/ansible/roles/CoffeeITWorks.burp2_server
